export const projects: Project[] = [
  {
    id: "0",
    name: "Heart-to-Heart",
    description: "Addictive, unending game crafted from the ground up in 48 hours for a friendly game jam.",
    image: '/images/h2h.png',
    github: 'https://github.com/MiquilW/heart-to-heart',
    web: 'https://miquilw.github.io/heart-to-heart/',
    alt: 'Heart-to-Heart Thumbnail',
    tech: 'Python, PyGame, HTML/CSS, JavaScript',
  },
  {
    id: "1",
    name: "Music Website (Commisioned)",
    description: "Website created for a DJ. They sell all of their records on this site now.",
    image: '/images/spaceluvvr.png',
    github: 'https://github.com/MiquilW/spaceluvvr-website',
    web: 'https://spaceluvvr.com/',
    alt: 'Spaceluvvr Thumbnail',
    tech: 'HTML/CSS, JavaScript',
  },
  {
    id: "2",
    name: "My Portfolio Site",
    description: "Website created to showcase my work and thoughts. Constantly updated and added to.",
    image: '/images/portfolio.png',
    github: 'https://github.com/MiquilW/miquil',
    web: '',
    alt: 'Portfolio Thumbnail',
    tech: 'TypeScript, React, Next.js, Tailwind',
  },
]